/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TileDBRead */

#ifndef _Included_TileDBRead
#define _Included_TileDBRead
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TileDBRead
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TileDBRead_display
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
